let
    Source = iInterchangeInvoices,
    #"Added Index" = Table.AddIndexColumn(Source, "Index", 0, 1),
    #"Left Join dMerchanttAccounts" = Table.NestedJoin(#"Added Index",{"Outlet Id"},dMerchantAccounts_PSP,{"out_id"},"dMerchantAccounts",JoinKind.LeftOuter),
    #"Expanded dMerchantAccounts" = Table.ExpandTableColumn(#"Left Join dMerchanttAccounts", "dMerchantAccounts", {"company_code"}, {"company_code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Expanded dMerchantAccounts",{"company_code", "InvoiceSummary Id", "Invoice Company Name", "Invoice Period Year", "Invoice Period Name", "Invoice Period Start Date", "Invoice Period End Date", "Invoice BVUK Flag", "Outlet Id", "Store Code", "Billing Currency", "Billing CardName Summary", "Billing CardName Detail", "Sale Type", "Product Type", "Invoice Total to Bill", "Transaction Count", "Turnover", "IC Total Amount", "SF Total Amount", "Acq Total Amount", "Custom Total Amount", "Refund Fee Total Amount", "OCT Fee Total Amount", "Other Charge Total Amount", "Total Amount"}),
    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"Index", Order.Ascending}}),
    #"Removed Columns" = Table.RemoveColumns(#"Sorted Rows",{"Index"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"InvoiceSummary Id", "invoice_id"}, {"Invoice Company Name", "invoice_company_name"}, {"Invoice Period Year", "invoice_period_year"}, {"Invoice Period Name", "invoice_period_name"}, {"Invoice Period Start Date", "invoice_period_start_date"}, {"Invoice Period End Date", "invoice_period_end_date"}, {"Invoice BVUK Flag", "invoice_bvuk_flag"}, {"Outlet Id", "outlet_id"}, {"Store Code", "store_code"}, {"Billing Currency", "billing_currency"}, {"Billing CardName Summary", "billing_cardname_summary"}, {"Billing CardName Detail", "billing_cardname_detail"}, {"Sale Type", "sale_type"}, {"Product Type", "product_type"}, {"Invoice Total to Bill", "invoice_total"}, {"Transaction Count", "transaction_count"}, {"Turnover", "turnover"}, {"IC Total Amount", "ic_total_amount"}, {"SF Total Amount", "sf_total_amount"}, {"Acq Total Amount", "acq_total_amount"}, {"Custom Total Amount", "custom_total_amount"}, {"Refund Fee Total Amount", "refund_fee_total_amount"}, {"OCT Fee Total Amount", "oct_fee_total_amount"}, {"Other Charge Total Amount", "other_charge_total_amount"}, {"Total Amount", "total_amount"}})
in
    #"Renamed Columns"