let
    Source = Excel.CurrentWorkbook(){[Name="tblTransSummary"]}[Content],
    #"Set Column Data Types" = Table.TransformColumnTypes(Source,{{"Merchant Code", type text}, {"OrderCode", type text}, {"Date", type datetime}, {"PaymentMethod", type text}, {"Status", type text}, {"CurrencyCode", type text}, {"Amount", type number}, {"Commission", type number}, {"Batch ID", Int64.Type}, {"Refusal Reason", type text}}),
    #"Filter [Status]" = Table.SelectRows(#"Set Column Data Types", each ([Status] = "CAPTURED" or [Status] = "SETTLED" or [Status] = "SETTLED_BY_MERCHANT")),
    #"Add Custom [Amount]" = Table.AddColumn(#"Filter [Status]", "Custom",
        each if [Status] = "CAPTURED" then [Amount]
        else if [Status] = "SETTLED" then [Amount]
        else if [Status] = "SETTLED_BY_MERCHANT" then [Amount] * -1
        else null),
    #"Reordered Columns" = Table.ReorderColumns(#"Add Custom [Amount]",{"Merchant Code", "OrderCode", "Date", "PaymentMethod", "Status", "CurrencyCode", "Amount", "Custom", "Commission", "Batch ID", "Refusal Reason"}),
    #"Removed Original [Amount]" = Table.RemoveColumns(#"Reordered Columns",{"Amount"}),
    #"Renamed Custom [Amount]" = Table.RenameColumns(#"Removed Original [Amount]",{{"Custom", "Amount"}}),
    #"Set [Amount] Data Type" = Table.TransformColumnTypes(#"Renamed Custom [Amount]",{{"Amount", type number}}),
    #"Sorted Rows" = Table.Sort(#"Set [Amount] Data Type",{{"Merchant Code", Order.Ascending}, {"OrderCode", Order.Ascending}, {"Date", Order.Ascending}})
in
    #"Sorted Rows"