let
    Source = Folder.Files("C:\Users\financetemp\Dropbox\Revenue bridge\Revenue Bridge 2017\Raw Data\Acquirer Batch Detail"),
    #"[Filter File Name]" = Table.SelectRows(Source, each Text.Contains([Name], "Acquirer Batch Detail")),
    #"[Filter File Extension]" = Table.SelectRows(#"[Filter File Name]", each [Extension] = ".csv"),
    #"Removed Columns" = Table.RemoveColumns(#"[Filter File Extension]",{"Date accessed", "Date modified", "Date created", "Attributes", "Folder Path"}),
    #"Invoke Custom Function1" = Table.AddColumn(#"Removed Columns", "Transform File from Acquirer Batch Detail (Import)", each #"Transform File from Acquirer Batch Detail (Import)"([Content])),
    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File from Acquirer Batch Detail (Import)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File from Acquirer Batch Detail (Import)", Table.ColumnNames(#"Transform File from Acquirer Batch Detail (Import)"(#"Sample File (4)"))),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Expanded Table Column1", "Account", Splitter.SplitTextByEachDelimiter({"^"}, QuoteStyle.Csv, false), {"Account.1", "Account.2"}),
    #"[Set Column Data Types]" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Batch Id", Int64.Type}, {"Event Type", type text}, {"Order Code", type text}, {"BackOffice Code", type text}, {"Payment Method", type text}, {"Date", type date}, {"Currency", type text}, {"Amount", type number}}),
    #"Renamed Columns" = Table.RenameColumns(#"[Set Column Data Types]",{{"Account.1", "Bank Account"}, {"Account.2", "Account No."}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","CAPTURED","AUTHORISED",Replacer.ReplaceText,{"Event Type"}),
    #"[Filter Currency]" = Table.SelectRows(#"Replaced Value", each ([Currency] = "SEK")),
    #"[Filter Account No.]" = Table.SelectRows(#"[Filter Currency]", each not Text.Contains([#"Account No."], "paypal")),
    #"Filter [Payment Method]" = Table.SelectRows(#"[Filter Account No.]", each ([Payment Method] <> "PAYPAL-EXPRESS")),
    #"Merge [Order Codes] Table" = Table.NestedJoin(#"Filter [Payment Method]",{"Order Code", "Payment Method", "Event Type"},#"Order Codes (Appended)",{"OrderCode", "PaymentMethod", "Status"},"NewColumn",JoinKind.LeftOuter),
    #"Expand [Merchant Code]" = Table.ExpandTableColumn(#"Merge [Order Codes] Table", "NewColumn", {"Merchant Code"}, {"Merchant Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Expand [Merchant Code]",{"Merchant Code", "Batch Id", "Bank Account", "Account No.", "Event Type", "Order Code", "BackOffice Code", "Payment Method", "Date", "Currency", "Amount"}),
    #"Merge [Merchant ID] Table" = Table.NestedJoin(#"Reordered Columns",{"Merchant Code"},#"Merchant ID (Table)",{"Merchant Code"},"NewColumn",JoinKind.LeftOuter),
    #"Expand [Merchant ID]" = Table.ExpandTableColumn(#"Merge [Merchant ID] Table", "NewColumn", {"Company ID going forward"}, {"Company ID going forward"}),
    #"Rename [Merchant ID]" = Table.RenameColumns(#"Expand [Merchant ID]",{{"Company ID going forward", "Merchant ID"}}),
    #"Merge [Acquirer Batch Periods]" = Table.NestedJoin(#"Rename [Merchant ID]",{"Merchant Code", "Batch Id"},#"Acquirer Batch Periods",{"Merchant Code", "Batch Id"},"Acquirer Batch Periods",JoinKind.LeftOuter),
    #"Expand [Batch Total]" = Table.ExpandTableColumn(#"Merge [Acquirer Batch Periods]", "Acquirer Batch Periods", {"Amount"}, {"Amount.1"}),
    #"Rename [Batch Total]" = Table.RenameColumns(#"Expand [Batch Total]",{{"Amount.1", "Batch Total"}}),
    #"Merge [Acquirer Batch Totals]" = Table.NestedJoin(#"Rename [Batch Total]",{"Merchant ID", "Date"},#"Acquirer Batch Totals (Reference)",{"Merchant ID", "Trading Date"},"Acquirer Batch Totals (Reference)",JoinKind.LeftOuter),
    #"Expand [Date Total]" = Table.ExpandTableColumn(#"Merge [Acquirer Batch Totals]", "Acquirer Batch Totals (Reference)", {"Date Total"}, {"Date Total"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Expand [Date Total]",{"Merchant Code", "Merchant ID", "Batch Id", "Bank Account", "Account No.", "Event Type", "Order Code", "BackOffice Code", "Payment Method", "Currency", "Amount", "Batch Total", "Date Total", "Date"}),
    #"Rename [Trading Date]" = Table.RenameColumns(#"Reordered Columns1",{{"Date", "Trading Date"}})
in
    #"Rename [Trading Date]"